apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: torinos-analyzer
  namespace: torinos-analyzer
  labels:
    name: torinos-analyzer
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      name: torinos-analyzer
      labels:
        name: torinos-analyzer
        role: web
    spec:
      containers:
        - image: torinosio/analyzer:latest
          name: torinos-analyzer
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: hello
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
